### ISSUE TITLE
Debug hints?

### ISSUE THREAD

**Issue by SzymonSlupik** [tsowell/avr-hdmi-cec-volume#2]
Hi Thomas,
I have prepared a test board following your sch (thanks for fixing the pin labels!). In principle it works, but the final results show some potential issues with my setup. Do you have any hints where to look for / what to try?

I have a Philips TV with 3 devices connected:
- Apple TV
- Raspberry Pi (running CEC Client)
- Your ATTINY board

The CEC Client scan produces this output:
```
pi@redpi:~ $ echo "scan" | cec-client RPI -s -d 1
opening a connection to the CEC adapter...
requesting CEC bus information ...
ERROR:   [           10612]     failed to request the physical address
CEC bus information
===================
device #1: Recorder 1
address:       2.0.0.0
active source: no
vendor:        Pulse Eight
osd string:    CECTester
CEC version:   1.4
power status:  on
language:      eng


device #4: Playback 1
address:       3.0.0.0
active source: no
vendor:        Apple
osd string:    Bedroom
CEC version:   2.0
power status:  on
language:      ???


device #5: Audio
address:       f.f.f.f
active source: no
vendor:        Unknown
osd string:    Audio
CEC version:   unknown
power status:  unknown
language:      ???


currently active source: unknown (-1)
```

At the same time the debug output shows this:

```
<int>
<int>
e0
e0
e0
min
error -1
min
error -1
e0
<int>
e0
11
min
error -1
min
error -1
11
11
min
error -1
ee
min
error -1
1f:84:20:00:01
10
10
10
10
<int>
10
10
min
error -1
10
10
10
min
error -1
12
12
13
13
13
14
15
min
error -1
16
16
17
min
error -1
17
<int>
min
error -1
18
min
error -1
19
19
1a
min
error -1
1a
1b
1b
1b
1c
1c
1c
min
error -1
<int>
min
error -1
1d
1e
1e
1e
1f:85
<int>
min
error -1
<int>
14:8c
min
error -1
14:83
4f:84:30:00:04
14:9f
min
error -1
14:8f
<int>
min
error -1
41:47:42:65:64:72:6f:6f:6d
14:91
max
error -1
min
error -1
15:8c
<vendor id>
<int>
15:8c
<vendor id>
<int>
15:8c
<vendor id>
<int>
min
error -1
max
error -1
min
error -1
<int>
15:83
<phys address>
<int>
min
error -1
min
error -1
min
error -1
min
error -1
15:8f
<power status>
<int>
min
error -1
15:46
<osd name>
<int>
min
error -1
15:91
<int>
15:91
<int>
1f:85
<int>
min
error -1
<int>
```

Any hints where to start / what to look for are appreciated!

**Comment by SzymonSlupik** [comment]
OK it seems I am getting some progress now - the issue was I was using wrong GND. Now the signal seems quite stable and the CEC decoding works - the debug output looks like this:
```
1e
1e
1e
1f:85
<int>
1f:85
<int>
14:8c
4f:87:00:10:fa
14:83
4f:84:30:00:04
14:9f
41:9e:06
14:8f
41:90:00
<int>
14:46
41:47:42:65:64:72:6f:6f:6d
14:91
41:00:91:00
15:8c
<vendor id>
15:83
<phys address>
<int>
15:83
<phys address>
<int>
15:9f
<int>
15:9f
<int>
15:8f
<power status>
<int>
15:46
<osd name>
15:91
<int>
15:91
<int>
1f:85
<int>
1f:85
<int>

```
Raspberry PI cec-client is still reporting some issues - like the f.f.f.f address. 
```
pi@redpi:~ $ echo "scan" | cec-client RPI -s -d 1
opening a connection to the CEC adapter...
requesting CEC bus information ...
ERROR:   [            9393]     failed to request the physical address
CEC bus information
===================
device #1: Recorder 1
address:       2.0.0.0
active source: no
vendor:        Pulse Eight
osd string:    CECTester
CEC version:   1.4
power status:  on
language:      eng


device #4: Playback 1
address:       3.0.0.0
active source: no
vendor:        Apple
osd string:    Bedroom
CEC version:   2.0
power status:  on
language:      ???


device #5: Audio
address:       f.f.f.f
active source: no
vendor:        Unknown
osd string:    PioneerSX-950
CEC version:   unknown
power status:  on
language:      ???


currently active source: unknown (-1)
pi@redpi:~ $
```
I need to dive deeper into the CEC protocol to figure out what is going on. Still any hints would be appreciated.

**Comment by tsowell** [comment]
Hi Szymon,

I'm glad to hear that you're making progress!  I don't know if I will be much help, but I do have a couple of suggestions:

1. Try disabling debug output.  I don't know how quickly the Pi expects responses, but it does take a long time to write out to the UART.  The debug output might introduce enough delay to affect CEC command timing.

2. Try connecting the Pi directly to the ATTINY board to see if it works better with no other devices on the CEC bus.

I will try to get my device connected to a Pi this weekend so I can share the expected cec-client output, but let me know if you make any more progress in the meantime.  Good luck!

**Comment by SzymonSlupik** [comment]
I got rid of the [ERROR: [9393] failed to request the physical address] - the response was using a wrong opcode (0x87 vs 0x84). Reported this as #3 
Still don't understand why it reports "address: f.f.f.f". Parameters mismatch in the response message?
```
pi@redpi:~ $ echo "scan" | cec-client RPI -s -d 1
opening a connection to the CEC adapter...
requesting CEC bus information ...
CEC bus information
===================
device #1: Recorder 1
address:       1.0.0.0
active source: no
vendor:        Pulse Eight
osd string:    CECTester
CEC version:   1.4
power status:  on
language:      eng


device #5: Audio
address:       f.f.f.f
active source: no
vendor:        Unknown
osd string:    PioneerSX-950
CEC version:   unknown
power status:  on
language:      ???


currently active source: unknown (-1)
pi@redpi:~ $
```

**Comment by SzymonSlupik** [comment]
Have found (what seems to be) another opcode mismatch - 0x70 should be 0x7d. At least after this change I started seeing <vol up> / <vol down> coming from my Apple TV. Reported as #4

**Comment by SzymonSlupik** [comment]
It seems I am now done with my HDMI CEC projects for some time. Thanks for setting a great foundation, Thomas. Based on your work I have created two new projects:
- [CEC-Tiny-Pro](https://github.com/SzymonSlupik/CEC-Tiny-Pro), serving mostly as a playground / sniffer / debugger
- [CEC-Tiny](https://github.com/SzymonSlupik/CEC-Tiny) - an ATTINY25-based implementation of device on/off

Hope you are OK with how I have attributed your work. If you have any suggestions WRT the copyright and other attributions - please let me know, otherwise please close this issue, as I believe the "debugging" part has now been addressed.

**Comment by tsowell** [comment]
Hi Szymon, that's a beautiful vintage TV.  It's cool that you found a way to give it new life.  Thanks for the attribution in your projects!  I'm so glad you found my work useful.

Sorry for not getting back to you sooner, but I'll close this issue now.
