### ISSUE TITLE
report_physical_address should be 0x84

### ISSUE THREAD

**Issue by SzymonSlupik** [tsowell/avr-hdmi-cec-volume#3]
report_physical_address uses opcode 0x87 (Device Vendor ID). I think it should be using 0x84.

**Comment by tsowell** [comment]
You're right, sorry about that.  It looks like I copied report_physical_address from device_vendor_id and never updated the contents.  My TV doesn't seem to mind, but I'm not surprised that other devices have problems with it.  684e8c1 is an attempt to correctly support the Report Physical Address message, but I haven't tested it yet.

**Comment by tsowell** [comment]
Looks like 684e8c1 fixes this.  I'm going to leave the issue open I've tested it on my setup and merged it.

**Comment by SzymonSlupik** [comment]
The fix is OK - thanks!
