### ISSUE TITLE
<max> error returned repeatedly

### ISSUE THREAD

**Issue by SzymonSlupik** [tsowell/avr-hdmi-cec-volume#5]
When I have the ATTINY connected to the CEC output of an Apple TV, on top of properly reported messages it reports a sequence (typically 3 in a row) of <max> errors.

This happens upon powering up (I have modified the debug printout a bit, but I think it is clear what the code reports):
```
Rx-> 45:7d audio status?
<-Tx 5f:72 set audio
Rx-> 4f:90:00 pwr
max E -1
max E -1
max E -1
```
and upon powering down (sleep mode):
```
Rx-> 4f:36 all sby
max E -1
max E -1
max E -1
```
The captured waveform of a single "max error" frame looks like this:

![max error -1](https://user-images.githubusercontent.com/14368445/135095676-3a7f8d0b-f684-4d03-87c4-5892c9208619.PNG)

Any ideas what is going on and how to fix this?

**Comment by tsowell** [comment]
This looks to me like an aborted frame: start bit, initiator=0b0100, destination=0b0000, EOM=0 (not end-of-message), ACK=1 (not acknowledged), then free time followed by a new frame.  My best guess is that the initiator is retransmitting the frame after the header block was not acknowledged (probably because there is no device on the bus with address 0).  It's not clear to me from the spec whether or not an initiator should retransmit a frame before it finishes sending it the first time, but I think the behavior on the ATTINY end is correct regardless: move on and start reading the next frame.  Do you see any issues with that?

**Comment by SzymonSlupik** [comment]
Yes, the aborted frame due to no ACK from 0 is probably the correct explanation. When I added ACKing messages addressed to 0, the (max) stopped popping up, and instead I see it is sending 04 (image view on) at startup and 9d (inactive source) on shutdown, which makes sense.

In my particular case I intend to hook into the 36 (all standby) messages sent by Apple TV when powering off, to power off the other equipment. Unfortunately the (all standby) was not received reliably all the time.

I think I managed to reproduce this behavior. Below several CEC traffic sequences are captured.

```
[Apple TV startup]
Rx-> 45:7d audio status?
<-Tx 5f:72 set audio
Rx-> 4f:90:00 pwr
max E -1
max E -1
max E -1
max E -1
max E -1

[Volume up/down pressed on the Apple remote]
Rx-> 45:44:41 v up
Rx-> 45:45 rel
Rx-> 45:44:42 v dn
Rx-> 45:45 rel

[Apple TV shutdown - the STANDBY message received properly]
Rx-> 4f:36 all sby
max E -1
max E -1
max E -1
max E -1

[Apple TV startup]
Rx-> 45:7d audio status?
<-Tx 5f:72 set audio
Rx-> 4f:90:00 pwr
max E -1
max E -1
max E -1
max E -1
max E -1

[Apple TV shutdown - no STANDBY message received]
max E -1
max E -1
max E -1

[Apple TV startup]
Rx-> 45:7d audio status?
<-Tx 5f:72 set audio
Rx-> 4f:90:00 pwr
max E -1
max E -1
max E -1
max E -1
max E -1

[Apple TV shutdown - no STANDBY message received]
max E -1
max E -1
max E -1

[Apple TV startup]
Rx-> 45:7d audio status?
<-Tx 5f:72 set audio
Rx-> 4f:90:00 pwr
max E -1
max E -1
max E -1
max E -1

[Volume up/down pressed on the Apple remote]
Rx-> 45:44:41 v up
Rx-> 45:45 rel
Rx-> 45:44:42 v dn
Rx-> 45:45 rel

[Apple TV shutdown - the STANDBY message received properly]
Rx-> 4f:36 all sby
max E -1
max E -1
max E -1

[Apple TV startup]
Rx-> 45:7d audio status?
<-Tx 5f:72 set audio
Rx-> 4f:90:00 pwr
max E -1
max E -1
max E -1
max E -1
max E -1

[Other CEC traffic injected from another device (Raspberry Pi)]
Rx-> 1f:84:30:00:01 addr map
Rx-> 1f:85 sys discovery
Rx-> 4f:82:10:00 otp
Rx-> 14:8c vid?
Rx-> 4f:87:00:10:fa vid
Rx-> 14:9f CEC v?
Rx-> 41:9e:06 CEC v
Rx-> 14:46 osd?
Rx-> 41:47:42:65:64:72:6f:6f:6d osd
Rx-> 14:91 lang?
Rx-> 41:00:91:00 ???
Rx-> 15:8c vid?
<-Tx 5f:87 vid
Rx-> 15:83 phys addr?
<-Tx 5f:84 phys addr
Rx-> 15:9f CEC v?
Rx-> 15:9f CEC v?
Rx-> 15:8f pwr?
<-Tx 51:90 rep pwr
Rx-> 15:46 osd?
<-Tx 51:47 osd
Rx-> 15:91 lang?
Rx-> 15:91 lang?
Rx-> 18:8c vid?
Rx-> 8f:87:00:1a:11 ???
Rx-> 18:83 phys addr?
Rx-> 8f:84:50:00:04 addr map
Rx-> 18:9f CEC v?
Rx-> 81:9e:05 CEC v
Rx-> 18:8f pwr?
Rx-> 81:90:00 pwr
Rx-> 18:46 osd?
Rx-> 81:47:43:68:72:6f:6d:65:63:61:73:74 osd
Rx-> 18:91 lang?
Rx-> 81:00:91:04 abort

[Apple TV shutdown - the STANDBY message received properly]
Rx-> 4f:36 all sby
max E -1
max E -1

```

There clearly is a pattern:

1. If the AppleTV is shut down immediately after the startup (no CEC messages in between), the standby message is not received. The last received message before the shutdown is the (max) error - the aborted message. And it causes the next proper message - the (standby) in my case - to be dropped. 
2. If there is **any** CEC traffic in-between the startup and the shutdown, the (standby) message is received properly. This "in-between" traffic can be anything - either generated by the AppleTV or an another device.

My hypothesis is the ATTINY code does not recover properly from an aborted message and as a result the next message after the aborted one (the all standby in my case) is dropped (I believe AppleTV is still sending it properly). I do not fully follow what happens in the code after the (max) error, but it seems it may cause the next message after that to be dropped.

**Comment by SzymonSlupik** [comment]
I no longer have these issues. It might have been a hardware issue (no calibrated oscillator?). I have gone through multiple HW revisions on my end and have not seen these errors for a long time now. I think this can be closed.
